CREATE ROLE patient;
CREATE ROLE doctor;
CREATE ROLE admin;
CREATE ROLE head_doctor;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO patient;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO patient;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO doctor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO doctor;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO head_doctor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO head_doctor;

CREATE USER admin1 WITH PASSWORD 'admin';
GRANT admin TO admin1;

CREATE USER head_doctor1 WITH PASSWORD 'head_doctor';
GRANT head_doctor TO head_doctor1;
